### ISSUE TITLE
Generic "help" message is also too long (the one about valid keywords)

### ISSUE THREAD

**Issue by ghost** [mwana/mwana#2]

**Comment by nchimunya** [comment]
Changed to:
Invalid Keyword. Valid keywords are JOIN, AGENT, CHECK, RESULT, SENT, ALL, CBA, BIRTH and CLINIC. Respond with any keyword or HELP for more information.

**Comment by nchimunya** [comment]
e05d329aa55124af90fb50f5d0ab770a3d09fc3d
