### ISSUE TITLE
add vim modeline to the top of all .py files in the project

### ISSUE THREAD

**Issue by tobiasmcnulty** [mwana/mwana#40]
per Merrick's request.

The modeline should read:

 # vim: ai ts=4 sts=4 et sw=4

Evan says: "in spite of its name, vim mode lines arent catering to a specific group. theyre not exclusive to vim, they just happen to be the standard -- emacs, eclipse, textmate, etc all pick up vim mode lines and use the per-file mode line settings to override the editor's defaults. having a correct vim mode line will ensure that eclipse wont let you mess up the formatting prescribed at the top of the file"

**Comment by merrick** [comment]
is this hard to do? or is this just a 10 minute fix

**Comment by jawspeak** [comment]
See pull request: https://github.com/mwana/mwana/pull/78

**Comment by tsinkala** [comment]
I think this is completed
