### ISSUE TITLE
remove results from MoH that are for clinics outside the pilot

### ISSUE THREAD

**Issue by tobiasmcnulty** [mwana/mwana#44]
Results were added to the MoH database before the script was modified to filter by clinic.  We should probably remove the results from the MoH database that are for these other clinics.

**Comment by tobiasmcnulty** [comment]
note that there are 10 clinics being piloted for Southern Province (via UTH) as well, and these should stay in the DB

**Comment by tsinkala** [comment]
The said results were removed
