### ISSUE TITLE
Error in displying an admin page

### ISSUE THREAD

**Issue by tsinkala** [mwana/mwana#45]
TemplateSyntaxError: Caught an exception while rendering: Failed lookup for key [request] in u'[{\'block\': <Block Node: header. Contents: [<Text Node
: \'\n\t\t\t<div id="header">\n\t\t\t\'>, <django.templatetags.i18n.TranslateNode object at 0x03479510>, <Text Node: \'" href="/">\n\t\t\t\t\t\t\t<spa
n>\'>, <Block Node: auth. Contents: [<Text Node: \'\n\t\t\t\t<div id="auth">\'>, <If node>, <Text Node: \'\n\t\t\t\t</div>\n\t\t\t\t\'>]>, <Text Node:
 \'\n\n\t\t\t\t\'>, <django.templatetags.tabs_tags.TabsNode object at 0x033E3E50>, <Text Node: \'\n\n\t\t\t\t<ul id="tabs">\'>, <For Node: for tab in
tabs, tail_len: 8>, <Text Node: \'\n\t\t\t\t</ul>\n\n\t\t\t\t\'>, <Block Node: page_tabs. Contents: [<Text Node: \'\n\t\t\t\t\'>]>, <Text Node: \'\n\t
\t\t</div>\n\t\t\t\'>]>}, {}]'

Original Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\django\template\debug.py", line 71, in render_node
    result = node.render(context)
  File "C:\rapidSMS\mwana\mwana\submodules\rapidsms\lib\rapidsms\templatetags\tabs_tags.py", line 92, in render
    request = Variable("request").resolve(context)
  File "C:\Python26\lib\site-packages\django\template__init__.py", line 687, in resolve
    value = self._resolve_lookup(context)
  File "C:\Python26\lib\site-packages\django\template__init__.py", line 740, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key [%s] in %r", (bit, current)) # missing attribute
VariableDoesNotExist: Failed lookup for key [request] in u'[{\'block\': <Block Node: header. Contents: [<Text Node: \'\n\t\t\t<div id="header">\n\t\t\
t\'>, <django.templatetags.i18n.TranslateNode object at 0x03479510>, <Text Node: \'" href="/">\n\t\t\t\t\t\t\t<span>\'>, <Block Node: auth. Contents:
[<Text Node: \'\n\t\t\t\t<div id="auth">\'>, <If node>, <Text Node: \'\n\t\t\t\t</div>\n\t\t\t\t\'>]>, <Text Node: \'\n\n\t\t\t\t\'>, <django.template
tags.tabs_tags.TabsNode object at 0x033E3E50>, <Text Node: \'\n\n\t\t\t\t<ul id="tabs">\'>, <For Node: for tab in tabs, tail_len: 8>, <Text Node: \'\n
\t\t\t\t</ul>\n\n\t\t\t\t\'>, <Block Node: page_tabs. Contents: [<Text Node: \'\n\t\t\t\t\'>]>, <Text Node: \'\n\t\t\t</div>\n\t\t\t\'>]>}, {}]'

**Comment by tobiasmcnulty** [comment]
what is the admin page being rendered?

**Comment by tsinkala** [comment]
The admin pages were showing fine. The error was coming when performing some action (which I cannot remember exactly). Even so, I have realised I din't have the latest files in "mwana\mwana\submodules\rapidsms" affecting 30 files.

**Comment by tsinkala** [comment]
This was coming most likely due to db integrity errors to do with two active contacts sharing the same connection identity (phone number) . This was rectified
