### ISSUE TITLE
warning about use of deprecated object

### ISSUE THREAD

**Issue by tsinkala** [mwana/mwana#46]
Got following exception:

C:\rapidSMS\mwana\mwana\submodules\rapidsms\lib\rapidsms\contrib\scheduler\app.py:116: DeprecationWarning: BaseException.message has been deprecated a
s of Python 2.6
  e.message))
Traceback (most recent call last):
  File "C:\Python26\lib\logging\handlers.py", line 865, in emit
    smtp = smtplib.SMTP(self.mailhost, port)
  File "C:\Python26\lib\smtplib.py", line 239, in **init**
    (code, msg) = self.connect(host, port)
  File "C:\Python26\lib\smtplib.py", line 295, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Python26\lib\smtplib.py", line 273, in _get_socket
    return socket.create_connection((port, host), timeout)
  File "C:\Python26\lib\socket.py", line 514, in create_connection
    raise error, msg
error: [Errno 10061] No connection could be made because the target machine actively refused it
[router]: Problem in scheduler for: mwana.apps.labresults.tasks.send_changed_records_notification: Months:(All), Days of Month:(All), Days of Week:(Al
l), Hours:(*), Minutes:(1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59). pygsm

**Comment by tobiasmcnulty** [comment]
This isn't really a problem as we have no plans to use anything other than Python 2.6.  If anything it's a RapidSMS issue.

**Comment by tsinkala** [comment]
Obsolete
