### ISSUE TITLE
URGENT - Reminders not being sent according to schedule

### ISSUE THREAD

**Issue by nchimunya** [mwana/mwana#67]
1. Reminders are being sent on wrong dates. E.g A notification for a birth that was on 4th August 2010 has been sent on 20th September 2010.
2. The appointment on all the reminders is being indicated as 6 days.

**Comment by czue** [comment]
It sounds like this was the 6 week notification, so probably the only issue is (2) above and we need to fix the message text.

**Comment by tsinkala** [comment]
issue did not exist
