### ISSUE TITLE
update REPORT handler to look at Result rather than Message model

### ISSUE THREAD

**Issue by tobiasmcnulty** [mwana/mwana#74]
The current implementation of the REPORT handler is not ideal because it relies on specific text appearing in the "sent messages" table in the database, rather than looking at the Result model, to determine how many results were sent out.  This is bad because (a) in Malawi, the terms "Detected" and "NotDetected" are not used, and (b) the report might return false results in case the same results are sent out more than once (e.g., via RESULT or in the case where a result changes and is resent).

Modify the Result model to include any extra data necessary & update the report handler to look there instead of at the message model.

**Comment by tsinkala** [comment]
completed
