### ISSUE TITLE
App to handle SMSs from mobile service providers

### ISSUE THREAD

**Issue by tsinkala** [mwana/mwana#81]
create an app to be handling SMSs from mobile service providers. Such messages sometimes cause a loop of of error message exchange between Mwana and the service provider. e.g

.....
[MTN to Mwana ]-->Sorry,the format of your input is invalid please re-enter.
[Mwana to MTN]-->Invalid Keyword. Valid keywords are JOIN, AGENT, CHECK, RESULT, ...
[MTN to Mwana ]-->Sorry,the format of your input is invalid please re-enter.
[Mwana to MTN]-->Invalid Keyword. Valid keywords are JOIN, AGENT, CHECK, RESULT, ...
[MTN to Mwana ]-->Sorry,the format of your input is invalid please re-enter.
[Mwana to MTN]-->Invalid Keyword. Valid keywords are JOIN, AGENT, CHECK, RESULT, ...
[MTN to Mwana ]-->Sorry,the format of your input is invalid please re-enter.
[Mwana to MTN]-->Invalid Keyword. Valid keywords are JOIN, AGENT, CHECK, RESULT, ...
[MTN to Mwana ]-->Sorry,the format of your input is invalid please re-enter.
.....

**Comment by adewinter** [comment]
Some ideas: 
- We could place a limit on the number of times in a day that the help message gets sent out
- Blacklist the number (anything sent from that number gets ignored)
- Contact the ISP and get them to stop sending us messages.

I think the first two might be more generally useful...

**Comment by tsinkala** [comment]
On live server (production mode) all messages coming from a phone number with less than 7 characters or a phone number containing at least one letter are ignored.
